Linear algebra enables us to express complex expressions in a compact and universally understood way. Now that we have explored mathematical theory relating to matrices and are familiar with some functions which can be applied to these, our challenge is to code these in Python.

The section below will give a short demonstration of the mathematics behind each of the matrix operations. You then have the opportunity to try these out using Python.

In [51]:
#(1)Load libraries and create matrix:
%matplotlib inline
import sympy as sympy
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from scipy import *

#Create scalers - define scaler:
x = .5
print(x)

0.5


In [53]:
#Create vectors and lists using numpy for linear algebra. To create a vector apply the np.array function to a Python list ([1,2,3]).:
x_vector = np.array([1,2,3])
print(x_vector)


[1 2 3]


In [55]:
#The example above is a compact way to create a vector. You can also create a vector by defining a list and converting it to an array 👇:
c_list = [1,2]
print("The list:", len(c_list))
print("Has length:", len(c_list))

The list: 2
Has length: 2


In [57]:
c_vector = np.array(c_list)
print("The vector:", c_vector)
print("Has shape:", c_vector.shape)

The vector: [1 2]
Has shape: (2,)


In [59]:
#Note: A list is not an array. An array is not a list:
z = [5, 6]
print("This is a list, not an array:",z)
print(type(z))

This is a list, not an array: [5, 6]
<class 'list'>


In [30]:
#Define array x = np.array()
zarray = np.array(z)
print("This is an array, not a list", zarray)
print(type(zarray))

This is an array, not a list [5 6]
<class 'numpy.ndarray'>


In [61]:
#Create a matrix:

b = list(zip(z,c_vector))
print(b)

#Note that the length of our zipped list is 2, not (2 by 2).

[(5, 1), (6, 2)]


In [63]:
#We can convert this list to a matrix:
A = np.array(b)
print( A)
print( type(A))
print( "A has shape:", A.shape)

[[5 1]
 [6 2]]
<class 'numpy.ndarray'>
A has shape: (2, 2)


In [65]:
#(2)Add or subtract matrices - We will start with two 2x2 matrices, where 2x2 indicates the number of rows x the number of columns:
result = A + 3
#or
result = 3 + A
print( result)

[[8 4]
 [9 5]]


In [47]:
#To subtract matrix B from matrix A, subtract each element of B from the corresponding element in A.
result = A - 3
#or
result = 3 - A
print( result)


[[-2  2]
 [-3  1]]


It is important to note that matrix addition and subtraction can only be defined when A and B are the same size. The matrices must be conformable since the operation is performed element by element. For addition and subtraction conformable means the matrices must each have the same number of rows, and each have the same number of columns.

Scalar multiplication is commutative: 3xA = Ax3

Note that the product is defined for a matrix of any dimension.f any dimension.

In [71]:
#Multiply a matrix by a scalar value
A = np.array([[5, 1], [6, 2]])
result = A * 3
print(result)

[[15  3]
 [18  6]]


Multiplying two matrices

Consider the following examples for multiplication

First of all we will multiply one of our matrices above by vector C. LaTeX: \Large \displaystyle C=\bigl( \begin{smallmatrix} c_{11} \\ 
  c_{21} 
\end{smallmatrix} \bigr)

We can multiply a matrix A2x2 and the vector C2x1. Unlike in the case of addition and subtraction above, here conformability depends only on the column dimension of the first operand and the row dimension of the second operand. In this case they both have the value 2, so these matrices can be multiplied.

In [75]:
#multiplying two matrices:
# Define matrices A and C
A = np.array([[5, 1], [6, 2]])
C = np.array([[2, 3], [1, 4]])

# Multiply A and C
result = A @ C  # or np.dot(A, C)
print(result)


[[11 19]
 [14 26]]


👆
The @ operator (or np.dot()) is used to multiply the two matrices.
The resulting matrix has dimensions determined by the rows of A and the columns of C

Division:
The term 'division' can be confusing when it comes to matrices. To carry this out we need to invert the matrix which is the divisor and then multiply.
The second option requires two steps: invert g and then multiply f times g-1. This is the method we use in the matrix world to carry out division. However, there is an additional consideration. We know that multiplication of matrices is not generally commutative so we must consider whether we want to pre multiply or post multiply.


In [79]:
A = np.arange(6).reshape((3,2))
B = np.arange(8).reshape((2,4))
print( "A is")
print( A)

print( "The Transpose of A is")
print( A.T)

A is
[[0 1]
 [2 3]
 [4 5]]
The Transpose of A is
[[0 2 4]
 [1 3 5]]


In [81]:
# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])  # 2x3 matrix (NxM)
B = np.array([[7, 8], [9, 10], [11, 12]])  # 3x2 matrix (MxP)

# Calculate (AB).T and B.T @ A.T
product_transpose = (A @ B).T
transpose_product = B.T @ A.T

# Print both results
print(product_transpose)
print("Is identical to:")
print(transpose_product)

[[ 58 139]
 [ 64 154]]
Is identical to:
[[ 58 139]
 [ 64 154]]
